### ISSUE TITLE
Creare script che cancella le righe inutili di intestazione dei CSV

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/arpasicilia_od#1]
Ad esempio le prime 6 righe di:

"NetC";"ARPA Sicilia";;;;;;;
"Stat";"VILLA AUGUSTA";;;;;;;
"Parm";"Benzene";"Benzene";"Benzene";"Benzene";"Benzene";"Benzene";"Benzene";"Benzene"
"PtId";"3";"3";"3";"3";"3";"3";"3";"3"
"Unit";"ug/m3 293K";;;"ug/m3 293K";;"ug/m3 293K";"ug/m3 293K";
"Field";"Aver";"SWrd";"MinT";"Min";"MaxT";"Max";"Sigma";"Samp"
"05/09/2015 00:00";;;;;;;;
"05/09/2015 01:00";"0.25395812";"80000000";"01:00";"0.0";"00:02";"4.8326762";"0.9897983";"720"
"05/09/2015 02:00";"0.84494699";"80000000";"02:00";"0.0";"01:17";"1.98060547";"0.87410642";"720"
"05/09/2015 03:00";"1.37112855";"80000000";"02:01";"0.0";"02:16";"3.8027603";"1.52284766";"720"
"05/09/2015 04:00";"0.00121023";"80000000";"04:00";"0.0";"03:00";"0.1584486";"0.01057578";"720"
"05/09/2015 05:00";"0.58846163";"80000000";"05:00";"0.0";"04:30";"2.29750267";"0.98001374";"720"
"05/09/2015 06:00";"0.82305098";"80000000";"06:00";"0.0";"05:59";"3.24819122";"1.39018815";"720"

**Comment by gpirrotta** [comment]
Ho creato uno scriptino in python che fa le seguenti cose:
- crea per ogni file letto un nuovo file con i dati puliti, cioè senza intestazioni
- rinomina il file da _enna_02092015.CSV_ a _20150902_enna.csv_ in modo da avere l'ordinamento alfanumerico uguale a quello cronologico, considerando anche i casi in cui nel nome del file sono presenti spazi
- prende in input la directory da esplorare e la directory da creare all'interno della quale inserisce i file puliti

**Eccezioni non gestite**
- la directory _altro_ contiene il file **Copia di trapani_082015.CSV** che lo script non gestisce
- probabile errore di data nel nome del file **gabbia 065092015.CSV**

**Comment by aborruso** [comment]
@gpirrotta bel lavoro!

A questo punto aspettiamo la definizione dello schema (#4), e si inserisce anche l'intestazione delle colonne.
