### ISSUE TITLE
Dataviz / Arrotondare i numeri nel tooltip (round)

### ISSUE THREAD

**Issue by nelsonmau** [SiciliaHub/arpasicilia_od#11]
ho visto questa soluzione per arrotondare i numeri nel tooltip

`tooltip: {
  valueDecimals: 2
},`

http://stackoverflow.com/questions/9085644/rounding-results-in-highcharts-jquery-script

**Comment by aborruso** [comment]
@patperu è per te, per questo http://www.covimo.de/arpa/MAria_report.html :)

**Comment by patperu** [comment]
Ciao @nelsonmau,
ho arrotondato i numeri nel tooltip (using `round`, because it's easier than changing the js-script).
