### ISSUE TITLE
Piccole novità sui dati ARPA

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/arpasicilia_od#9]
Scrivo anche qui un testo inviato in mailing list.

Vi scrivo per una piccola novità.

Da un po' di tempo il file opendata scaricabile in [questa pagina](http://www.arpa.sicilia.it/storage/#titoloinizio) (c'è il tasto in basso) è cambiato: infatti se scorrete sulla destra, trovate un po' tutti i dati in formato grezzo.

E' una sorta di xls che contiene dentro un csv. L'URL è [http://88.53.168.210/Bollettino2/MAria_report.xls](http://88.53.168.210/Bollettino2/MAria_report.xls), ma purtroppo nelle ultime settimana non è quasi mai raggiungibile.
Una copia non aggiornatissima la potete scaricare da [qui](https://github.com/SiciliaHub/arpasicilia_od/raw/master/script/MAria_report/MAria_report.xls).

Si presenta più o meno così:

![](http://i.imgur.com/ppoEVQN.png)

Non è adatto a farci subito delle elaborazioni: ci sono intestazioni da rimuovere, colonne totalmente vuote e/o inutili, nomi di colonna da normalizzare, ecc..

Però è un file che si presta a essere modificato e "ricostruito". Ho creato uno script in bash che consente di avere come output un file csv che può essere usato per analisi, grafici e mappe.
Questo file csv di output non è ancora la fine del mondo, così come non lo è lo script, ma consente di avere un file pronto per ulteriori elaborazioni.

L'output attuale dello script è [questo](https://github.com/SiciliaHub/arpasicilia_od/raw/master/script/MAria_report/MAria_report_04.csv), mentre lo script è [questo](https://github.com/SiciliaHub/arpasicilia_od/blob/master/script/MAria_report/arpa.sh).

Il file originario presenta due righe di intestazione:
- una con nome stazione, inquinante e unità di misura (ad esempio "partinico SO2(µg/m3)-2014");
- una con il tipo di misura in elenco (ad esempio "Max orario").

Ho ridotto tutto a una sola intestazione con un nome di questo tipo "partinico_SO2_Max_orario".
In [questo file](https://github.com/SiciliaHub/arpasicilia_od/blob/master/script/MAria_report/campi.csv) trovate il passaggio dalle due intestazioni alla singola.
## Lo script

E' basato su [csvkit](https://csvkit.readthedocs.org/en/0.9.1/), [agate](http://agate.readthedocs.org/en/1.3.0/) e sulle classiche meravigliose utility di Linux.

Fa essenzialmente questo:
- estrae soltanto le colonne che possono essere utili;
- rimuove le righe di intestazione;
- inserisce i nomi di colonna normalizzati;
- verifica quali colonne sono vuote;
- rimuove le colonne vuote.
## Le stazioni

Non ho verificato, ma dovrebbero essere sempre quelle di [questo elenco](https://github.com/SiciliaHub/arpasicilia_od/tree/master/data/stazioni).
## Futuro

Per il momento mi fermo qui, e lascio sopratutto a Patrick, Giovanni e Davide (che hanno lavorato sui primi dati ARPA) la palla.
Un grazie ad Antonio Conti di ARPA che mi ha dato informazioni utili sul file xls (ne è il creatore).

**Comment by patperu** [comment]
Ciao Andy,
grande lavoro! 
Based on your csv file I build an [R-script](https://github.com/patperu/arpasicilia_od/blob/master/script/MAria_report/MAria_report.md) and plot the PM10 values for Enna and Trapani. 
Ciao Patrick

**Comment by aborruso** [comment]
ciao @patperu usa come source sempre questo file http://dev.opendatasicilia.it/arpa/MAria_report.csv

L'ho appena aggiornato e ci sono dati più recenti.

Anche il tuo è un gran lavoro :)

**Comment by patperu** [comment]
Ciao @aborruso  ok, ho cambiato il url.
